# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
